// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class EBContact;
@class EBContact_Builder;
@class EBer;
@class EBer_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface EbbookRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface EBer : PBGeneratedMessage {
@private
  BOOL hasPhotostamp_:1;
  BOOL hasSeat_:1;
  BOOL hasReport_:1;
  BOOL hasGender_:1;
  BOOL hasBirthdate_:1;
  BOOL hasOffice_:1;
  BOOL hasDepartment_:1;
  BOOL hasCenter_:1;
  BOOL hasMobile_:1;
  BOOL hasVpmn_:1;
  BOOL hasTel_:1;
  BOOL hasMail_:1;
  BOOL hasBand_:1;
  BOOL hasTitle_:1;
  BOOL hasUid_:1;
  BOOL hasName_:1;
  BOOL hasId_:1;
  int32_t photostamp;
  NSString* seat;
  NSString* report;
  NSString* gender;
  NSString* birthdate;
  NSString* office;
  NSString* department;
  NSString* center;
  NSString* mobile;
  NSString* vpmn;
  NSString* tel;
  NSString* mail;
  NSString* band;
  NSString* title;
  NSString* uid;
  NSString* name;
  NSString* id;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasUid;
- (BOOL) hasTitle;
- (BOOL) hasBand;
- (BOOL) hasMail;
- (BOOL) hasTel;
- (BOOL) hasVpmn;
- (BOOL) hasMobile;
- (BOOL) hasCenter;
- (BOOL) hasDepartment;
- (BOOL) hasOffice;
- (BOOL) hasBirthdate;
- (BOOL) hasGender;
- (BOOL) hasReport;
- (BOOL) hasSeat;
- (BOOL) hasPhotostamp;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* uid;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* band;
@property (readonly, retain) NSString* mail;
@property (readonly, retain) NSString* tel;
@property (readonly, retain) NSString* vpmn;
@property (readonly, retain) NSString* mobile;
@property (readonly, retain) NSString* center;
@property (readonly, retain) NSString* department;
@property (readonly, retain) NSString* office;
@property (readonly, retain) NSString* birthdate;
@property (readonly, retain) NSString* gender;
@property (readonly, retain) NSString* report;
@property (readonly, retain) NSString* seat;
@property (readonly) int32_t photostamp;

+ (EBer*) defaultInstance;
- (EBer*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EBer_Builder*) builder;
+ (EBer_Builder*) builder;
+ (EBer_Builder*) builderWithPrototype:(EBer*) prototype;
- (EBer_Builder*) toBuilder;

+ (EBer*) parseFromData:(NSData*) data;
+ (EBer*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EBer*) parseFromInputStream:(NSInputStream*) input;
+ (EBer*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EBer*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EBer*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EBer_Builder : PBGeneratedMessage_Builder {
@private
  EBer* result;
}

- (EBer*) defaultInstance;

- (EBer_Builder*) clear;
- (EBer_Builder*) clone;

- (EBer*) build;
- (EBer*) buildPartial;

- (EBer_Builder*) mergeFrom:(EBer*) other;
- (EBer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EBer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (EBer_Builder*) setId:(NSString*) value;
- (EBer_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (EBer_Builder*) setName:(NSString*) value;
- (EBer_Builder*) clearName;

- (BOOL) hasUid;
- (NSString*) uid;
- (EBer_Builder*) setUid:(NSString*) value;
- (EBer_Builder*) clearUid;

- (BOOL) hasTitle;
- (NSString*) title;
- (EBer_Builder*) setTitle:(NSString*) value;
- (EBer_Builder*) clearTitle;

- (BOOL) hasBand;
- (NSString*) band;
- (EBer_Builder*) setBand:(NSString*) value;
- (EBer_Builder*) clearBand;

- (BOOL) hasMail;
- (NSString*) mail;
- (EBer_Builder*) setMail:(NSString*) value;
- (EBer_Builder*) clearMail;

- (BOOL) hasTel;
- (NSString*) tel;
- (EBer_Builder*) setTel:(NSString*) value;
- (EBer_Builder*) clearTel;

- (BOOL) hasVpmn;
- (NSString*) vpmn;
- (EBer_Builder*) setVpmn:(NSString*) value;
- (EBer_Builder*) clearVpmn;

- (BOOL) hasMobile;
- (NSString*) mobile;
- (EBer_Builder*) setMobile:(NSString*) value;
- (EBer_Builder*) clearMobile;

- (BOOL) hasCenter;
- (NSString*) center;
- (EBer_Builder*) setCenter:(NSString*) value;
- (EBer_Builder*) clearCenter;

- (BOOL) hasDepartment;
- (NSString*) department;
- (EBer_Builder*) setDepartment:(NSString*) value;
- (EBer_Builder*) clearDepartment;

- (BOOL) hasOffice;
- (NSString*) office;
- (EBer_Builder*) setOffice:(NSString*) value;
- (EBer_Builder*) clearOffice;

- (BOOL) hasBirthdate;
- (NSString*) birthdate;
- (EBer_Builder*) setBirthdate:(NSString*) value;
- (EBer_Builder*) clearBirthdate;

- (BOOL) hasGender;
- (NSString*) gender;
- (EBer_Builder*) setGender:(NSString*) value;
- (EBer_Builder*) clearGender;

- (BOOL) hasReport;
- (NSString*) report;
- (EBer_Builder*) setReport:(NSString*) value;
- (EBer_Builder*) clearReport;

- (BOOL) hasSeat;
- (NSString*) seat;
- (EBer_Builder*) setSeat:(NSString*) value;
- (EBer_Builder*) clearSeat;

- (BOOL) hasPhotostamp;
- (int32_t) photostamp;
- (EBer_Builder*) setPhotostamp:(int32_t) value;
- (EBer_Builder*) clearPhotostamp;
@end

@interface EBContact : PBGeneratedMessage {
@private
  PBAppendableArray * eberArray;
}
@property (readonly, retain) PBArray * eber;
- (EBer*)eberAtIndex:(NSUInteger)index;

+ (EBContact*) defaultInstance;
- (EBContact*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EBContact_Builder*) builder;
+ (EBContact_Builder*) builder;
+ (EBContact_Builder*) builderWithPrototype:(EBContact*) prototype;
- (EBContact_Builder*) toBuilder;

+ (EBContact*) parseFromData:(NSData*) data;
+ (EBContact*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EBContact*) parseFromInputStream:(NSInputStream*) input;
+ (EBContact*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EBContact*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EBContact*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EBContact_Builder : PBGeneratedMessage_Builder {
@private
  EBContact* result;
}

- (EBContact*) defaultInstance;

- (EBContact_Builder*) clear;
- (EBContact_Builder*) clone;

- (EBContact*) build;
- (EBContact*) buildPartial;

- (EBContact_Builder*) mergeFrom:(EBContact*) other;
- (EBContact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EBContact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)eber;
- (EBer*)eberAtIndex:(NSUInteger)index;
- (EBContact_Builder *)addEber:(EBer*)value;
- (EBContact_Builder *)setEberArray:(NSArray *)array;
- (EBContact_Builder *)setEberValues:(const EBer* *)values count:(NSUInteger)count;
- (EBContact_Builder *)clearEber;
@end

